# Generated by Django 5.0.3 on 2024-08-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.categories'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, help_text='Уникальный идентификатор категории для URL', max_length=150, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, help_text='Уникальный идентификатор категории для URL', max_length=150, unique=True, verbose_name='URL'),
        ),
    ]
