# Generated by Django 5.0.3 on 2024-08-20 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_anime_categories_alter_anime_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.studio'),
        ),
    ]
