# Generated by Django 5.0.3 on 2024-08-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_animeimages_review_season_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='episodes/videos/'),
        ),
    ]
