# Generated by Django 5.0.3 on 2024-08-24 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_episode_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime', verbose_name='Anime')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Anime View',
                'verbose_name_plural': 'Anime Views',
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
