# Generated by Django 5.0.3 on 2024-08-24 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_animeview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeview',
            name='viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Viewed At'),
        ),
    ]
