# Generated by Django 5.0.3 on 2024-08-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_animeview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='episodes/images/%Y/%m/%d/', verbose_name='Изоброжение'),
        ),
        migrations.AlterField(
            model_name='season',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaons', to='main.anime', verbose_name='Аниме'),
        ),
    ]
