# Generated by Django 5.0.3 on 2024-09-08 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_image_user_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='images',
            field=models.ImageField(blank=True, default='default_image/images.png', upload_to='episodes/images/%Y/%m/%d/', verbose_name='Изоброжение'),
        ),
        migrations.CreateModel(
            name='ActivateEmailModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=64)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
